export const START_FAVORITES_REQUEST = 'START_FAVORITES_REQUEST'
export const END_RETRIEVE_FAVORITES_REQUEST = 'END_RETRIEVE_FAVORITES_REQUEST'
export const END_SAVE_FAVORITES_REQUEST = 'END_SAVE_FAVORITES_REQUEST'
export const ADD_FAVORITE = 'ADD_FAVORITE'
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE'

export const START_WORD_REQUEST = 'START_WORD_REQUEST'
export const END_WORD_REQUEST = 'END_WORD_REQUEST'